security:
    providers:
        mysql:
            entity:
                class: App\Entity\User
                property: userName
    encoders:
        App\Entity\User:
            algorithm: bcrypt                     #algo de cryptage
            encode_as_base64: false
            iterations: 13
            
    firewalls:
        
        main:
            anonymous: true
            pattern: ^/
            form_login:
                login_path: login                 #route vers login
                
                check_path: login                 #route qui va vérifier que le login est ok ou pas
                default_target_path: home
            provider: mysql                       #les données proviennent de mysql (def ci dessus)
            
            logout:
                path:   /logout                   #route de déconnexion
                target: /                         #La deconnexion redirige vers
                
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER                     #deux roles pris en compte, admin > user
        
    access_control:                               #contrôle d'accès
      - { path: ^/admin, roles: ROLE_ADMIN}
      - { path: ^/visiteur, roles: ROLE_USER}